//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stuttering.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StutteringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StutteringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stuttering.Resx.StutteringResources", typeof(StutteringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 min.
        /// </summary>
        internal static string _1_min {
            get {
                return ResourceManager.GetString("1_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 min.
        /// </summary>
        internal static string _10_min {
            get {
                return ResourceManager.GetString("10_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 min.
        /// </summary>
        internal static string _2_min {
            get {
                return ResourceManager.GetString("2_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 min.
        /// </summary>
        internal static string _3_min {
            get {
                return ResourceManager.GetString("3_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 min.
        /// </summary>
        internal static string _4_min {
            get {
                return ResourceManager.GetString("4_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 min.
        /// </summary>
        internal static string _5_min {
            get {
                return ResourceManager.GetString("5_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 min.
        /// </summary>
        internal static string _6_min {
            get {
                return ResourceManager.GetString("6_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 min.
        /// </summary>
        internal static string _7_min {
            get {
                return ResourceManager.GetString("7_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 min.
        /// </summary>
        internal static string _8_min {
            get {
                return ResourceManager.GetString("8_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 min.
        /// </summary>
        internal static string _9_min {
            get {
                return ResourceManager.GetString("9_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        internal static string _lock {
            get {
                return ResourceManager.GetString("lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please attempt the question!.
        /// </summary>
        internal static string attempt {
            get {
                return ResourceManager.GetString("attempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please attempt all questions!.
        /// </summary>
        internal static string attempt_all {
            get {
                return ResourceManager.GetString("attempt_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breath In.
        /// </summary>
        internal static string breath_in {
            get {
                return ResourceManager.GetString("breath_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breath Out.
        /// </summary>
        internal static string breath_out {
            get {
                return ResourceManager.GetString("breath_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breathing Practice.
        /// </summary>
        internal static string breathing_practice {
            get {
                return ResourceManager.GetString("breathing_practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Pattern.
        /// </summary>
        internal static string change_pattern {
            get {
                return ResourceManager.GetString("change_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Pin.
        /// </summary>
        internal static string change_pin {
            get {
                return ResourceManager.GetString("change_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter.
        /// </summary>
        internal static string chapter {
            get {
                return ResourceManager.GetString("chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapters.
        /// </summary>
        internal static string chapters {
            get {
                return ResourceManager.GetString("chapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودہ پیٹرن درج کریں.
        /// </summary>
        internal static string current_pattern {
            get {
                return ResourceManager.GetString("current_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودہ پن درج کریں.
        /// </summary>
        internal static string current_pin {
            get {
                return ResourceManager.GetString("current_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیٹرن درج کریں.
        /// </summary>
        internal static string disable_pattern {
            get {
                return ResourceManager.GetString("disable_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Pin to disable.
        /// </summary>
        internal static string disable_pin {
            get {
                return ResourceManager.GetString("disable_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw again.
        /// </summary>
        internal static string draw_again {
            get {
                return ResourceManager.GetString("draw_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emotional Reactions.
        /// </summary>
        internal static string emotional_heading {
            get {
                return ResourceManager.GetString("emotional_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People who stutter may experience a variety of negative emotional reactions to the fact that they have difficulty in speaking. Examples include feelings of embarrassment, anxiety, and shame, which can lead to tension and struggle while speaking or attempts to avoid talking altogether..
        /// </summary>
        internal static string emotional_para {
            get {
                return ResourceManager.GetString("emotional_para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیٹرن درج کریں.
        /// </summary>
        internal static string enable_pattern {
            get {
                return ResourceManager.GetString("enable_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Pin to enable.
        /// </summary>
        internal static string enable_pin {
            get {
                return ResourceManager.GetString("enable_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter again.
        /// </summary>
        internal static string enter_again {
            get {
                return ResourceManager.GetString("enter_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیٹرن درج کریں.
        /// </summary>
        internal static string enter_pattern {
            get {
                return ResourceManager.GetString("enter_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پن درج کریں.
        /// </summary>
        internal static string enter_pin {
            get {
                return ResourceManager.GetString("enter_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exhale.
        /// </summary>
        internal static string exhale {
            get {
                return ResourceManager.GetString("exhale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facts about Stuttering.
        /// </summary>
        internal static string facts_heading {
            get {
                return ResourceManager.GetString("facts_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stutters can .
        /// </summary>
        internal static string facts_para_1_1 {
            get {
                return ResourceManager.GetString("facts_para_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to learn to overcome .
        /// </summary>
        internal static string facts_para_1_2 {
            get {
                return ResourceManager.GetString("facts_para_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stuttering.
        /// </summary>
        internal static string facts_para_1_3 {
            get {
                return ResourceManager.GetString("facts_para_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most stutterers .
        /// </summary>
        internal static string facts_para_2_1 {
            get {
                return ResourceManager.GetString("facts_para_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don’t stutter when alone .
        /// </summary>
        internal static string facts_para_2_2 {
            get {
                return ResourceManager.GetString("facts_para_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as they feel relaxed and focused and all brain resources are directed towards speech but among people the stuation is difficult. They feel stressed leading to stuttering .
        /// </summary>
        internal static string facts_para_2_3 {
            get {
                return ResourceManager.GetString("facts_para_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are .
        /// </summary>
        internal static string facts_para_3_1 {
            get {
                return ResourceManager.GetString("facts_para_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to situations when people don’t stutter .
        /// </summary>
        internal static string facts_para_3_2 {
            get {
                return ResourceManager.GetString("facts_para_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to like singing, speaking in unison with people or whispiring while speaking on phone, talking to a stranger or public speaking may enhance the stuttering..
        /// </summary>
        internal static string facts_para_3_3 {
            get {
                return ResourceManager.GetString("facts_para_3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are many .
        /// </summary>
        internal static string facts_para_4_1 {
            get {
                return ResourceManager.GetString("facts_para_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to famous people .
        /// </summary>
        internal static string facts_para_4_2 {
            get {
                return ResourceManager.GetString("facts_para_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to including ators scientists, musicians and politicians who stutter such as US President Joe Biden, Marilyn Monroe, James Earl Jones, Emily Blunt, Shaquille O’Neal, Darwin, Whinston Churchill. Actor Hiritik Karoshan and Rani Mukharji..
        /// </summary>
        internal static string facts_para_4_3 {
            get {
                return ResourceManager.GetString("facts_para_4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string go {
            get {
                return ResourceManager.GetString("go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchy.
        /// </summary>
        internal static string hierarchy_heading {
            get {
                return ResourceManager.GetString("hierarchy_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold 1.
        /// </summary>
        internal static string hold_1 {
            get {
                return ResourceManager.GetString("hold_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold 2.
        /// </summary>
        internal static string hold_2 {
            get {
                return ResourceManager.GetString("hold_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold On.
        /// </summary>
        internal static string hold_on {
            get {
                return ResourceManager.GetString("hold_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیٹرن غلط ہے۔.
        /// </summary>
        internal static string incorrect_pattern {
            get {
                return ResourceManager.GetString("incorrect_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پن غلط ہے۔.
        /// </summary>
        internal static string incorrect_pin {
            get {
                return ResourceManager.GetString("incorrect_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inhale.
        /// </summary>
        internal static string inhale {
            get {
                return ResourceManager.GetString("inhale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        internal static string instructions {
            get {
                return ResourceManager.GetString("instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Journey.
        /// </summary>
        internal static string journey_heading {
            get {
                return ResourceManager.GetString("journey_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s move on to some.
        /// </summary>
        internal static string lets_move {
            get {
                return ResourceManager.GetString("lets_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Type.
        /// </summary>
        internal static string lock_type {
            get {
                return ResourceManager.GetString("lock_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string management_heading {
            get {
                return ResourceManager.GetString("management_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment is most helpful when it focuses on more than just fluent speech. Since stuttering is more than just stuttering, treatment for stuttering should address more than just the observable speech disfluencies. Addressing the whole disorder is the key to helping people reduce the impact of stuttering on their lives Most people who stutter can speak without stuttering when they talk to themselves and when they sing or speak in unison with someone else, when they focus on more than just fluent speech and pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string management_para {
            get {
                return ResourceManager.GetString("management_para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Assessment     -.
        /// </summary>
        internal static string menu_assessment_close {
            get {
                return ResourceManager.GetString("menu_assessment_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Assessment     +.
        /// </summary>
        internal static string menu_assessment_open {
            get {
                return ResourceManager.GetString("menu_assessment_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Breathing Exercises.
        /// </summary>
        internal static string menu_breathing {
            get {
                return ResourceManager.GetString("menu_breathing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Self Evaluation of Fluency.
        /// </summary>
        internal static string menu_evaluation {
            get {
                return ResourceManager.GetString("menu_evaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string menu_exit {
            get {
                return ResourceManager.GetString("menu_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Flexible rate of speech.
        /// </summary>
        internal static string menu_flexible {
            get {
                return ResourceManager.GetString("menu_flexible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Management    -.
        /// </summary>
        internal static string menu_management_close {
            get {
                return ResourceManager.GetString("menu_management_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Management    +.
        /// </summary>
        internal static string menu_management_open {
            get {
                return ResourceManager.GetString("menu_management_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Easy Onset.
        /// </summary>
        internal static string menu_onset {
            get {
                return ResourceManager.GetString("menu_onset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Stutter Rater.
        /// </summary>
        internal static string menu_rater {
            get {
                return ResourceManager.GetString("menu_rater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Self Rating of Stuttering.
        /// </summary>
        internal static string menu_rating {
            get {
                return ResourceManager.GetString("menu_rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string menu_settings {
            get {
                return ResourceManager.GetString("menu_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مماثل.
        /// </summary>
        internal static string mismatched {
            get {
                return ResourceManager.GetString("mismatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostly.
        /// </summary>
        internal static string mostly {
            get {
                return ResourceManager.GetString("mostly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The one thing I’ve learned is that stuttering in public is never as bad as I fear it will be (John Stossel).
        /// </summary>
        internal static string motivaional_para_1 {
            get {
                return ResourceManager.GetString("motivaional_para_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep in mind that… the less you avoid words and situations, the less you will stutter in the long run (J.D. Williams).
        /// </summary>
        internal static string motivaional_para_2 {
            get {
                return ResourceManager.GetString("motivaional_para_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stuttering is ok because what I have to say is worth repeating (Anonymous).
        /// </summary>
        internal static string motivaional_para_3 {
            get {
                return ResourceManager.GetString("motivaional_para_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think that’s why I put my energy in making the Music (Kendrick Lamar).
        /// </summary>
        internal static string motivaional_para_4 {
            get {
                return ResourceManager.GetString("motivaional_para_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning how to help yourself should be the goal of every stutter (Malcom Fraser).
        /// </summary>
        internal static string motivaional_para_5 {
            get {
                return ResourceManager.GetString("motivaional_para_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivational Quotes.
        /// </summary>
        internal static string motivational_heading {
            get {
                return ResourceManager.GetString("motivational_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string never {
            get {
                return ResourceManager.GetString("never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw new Pattern.
        /// </summary>
        internal static string new_pattern {
            get {
                return ResourceManager.GetString("new_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new Pin.
        /// </summary>
        internal static string new_pin {
            get {
                return ResourceManager.GetString("new_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing is Wrong with Stutters.
        /// </summary>
        internal static string nothing_heading {
            get {
                return ResourceManager.GetString("nothing_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People aren’t doing anything wrong when they stutter; they are simply trying to talk, just like anyone else would do. If they feel embarrassed about their speech or ashamed of being different, then they are more likely to struggle with speaking or try to avoid talking. This makes the problem worse and increases the impact of the disorder. When people know that it is okay to stutter, then they can communicate more freely and more easily. They can say what they want to say, even if they sometimes say it disfl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nothing_para {
            get {
                return ResourceManager.GetString("nothing_para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occasionaly.
        /// </summary>
        internal static string occasionaly {
            get {
                return ResourceManager.GetString("occasionaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Often.
        /// </summary>
        internal static string often {
            get {
                return ResourceManager.GetString("often", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stuttering Overview.
        /// </summary>
        internal static string overview {
            get {
                return ResourceManager.GetString("overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stuttering is a speech disorder that involves frequent and significant problems with normal fluency and flow of speech..
        /// </summary>
        internal static string overview_definition {
            get {
                return ResourceManager.GetString("overview_definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern.
        /// </summary>
        internal static string pattern {
            get {
                return ResourceManager.GetString("pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        internal static string pin {
            get {
                return ResourceManager.GetString("pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not forget this pin. If you forget this pin, you won&apos;t be able to login to the app again..
        /// </summary>
        internal static string pin_description {
            get {
                return ResourceManager.GetString("pin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press D button when you stutter while speaking.
        /// </summary>
        internal static string rater_inst_d {
            get {
                return ResourceManager.GetString("rater_inst_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press RESET button to reset the timer and record.
        /// </summary>
        internal static string rater_inst_reset {
            get {
                return ResourceManager.GetString("rater_inst_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press S button when you spoke a syllable.
        /// </summary>
        internal static string rater_inst_s {
            get {
                return ResourceManager.GetString("rater_inst_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press START button to start the timer.
        /// </summary>
        internal static string rater_inst_start {
            get {
                return ResourceManager.GetString("rater_inst_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press STOP button to stop the timer.
        /// </summary>
        internal static string rater_inst_stop {
            get {
                return ResourceManager.GetString("rater_inst_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secs.
        /// </summary>
        internal static string secs {
            get {
                return ResourceManager.GetString("secs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Assessment.
        /// </summary>
        internal static string self_assessment {
            get {
                return ResourceManager.GetString("self_assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Fluent was I?.
        /// </summary>
        internal static string self_eva_q1 {
            get {
                return ResourceManager.GetString("self_eva_q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often did these features occur in my speech?
        ///•	Repitition
        ///•	Blockage
        ///•	Hesitation
        ///•	Prolongation.
        /// </summary>
        internal static string self_eva_q2 {
            get {
                return ResourceManager.GetString("self_eva_q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often did I use slowed speech?.
        /// </summary>
        internal static string self_eva_q3 {
            get {
                return ResourceManager.GetString("self_eva_q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How effective was my communication?.
        /// </summary>
        internal static string self_eva_q4 {
            get {
                return ResourceManager.GetString("self_eva_q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Were there any obstacles in communicating effectively?.
        /// </summary>
        internal static string self_eva_q5 {
            get {
                return ResourceManager.GetString("self_eva_q5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was there neck stiffness during my speech?.
        /// </summary>
        internal static string self_eva_q6 {
            get {
                return ResourceManager.GetString("self_eva_q6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have I observed rapid eye blinking, jaw jerking, foot taping and/or  other involuntary movements during the speech?.
        /// </summary>
        internal static string self_eva_q7 {
            get {
                return ResourceManager.GetString("self_eva_q7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Management.
        /// </summary>
        internal static string self_management {
            get {
                return ResourceManager.GetString("self_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 will be considered as less rate of suttering and 10 as severe intensity.
        /// </summary>
        internal static string self_rating_instruction {
            get {
                return ResourceManager.GetString("self_rating_instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate your stuttering intensity on the scale from 1 – 10.
        /// </summary>
        internal static string self_rating_q {
            get {
                return ResourceManager.GetString("self_rating_q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set time duration.
        /// </summary>
        internal static string set_time {
            get {
                return ResourceManager.GetString("set_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please start the stutter rater first!.
        /// </summary>
        internal static string start_stutter {
            get {
                return ResourceManager.GetString("start_stutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        internal static string stats {
            get {
                return ResourceManager.GetString("stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please stop the stutter rater first!.
        /// </summary>
        internal static string stop_stutter {
            get {
                return ResourceManager.GetString("stop_stutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Assessment.
        /// </summary>
        internal static string title_assessment {
            get {
                return ResourceManager.GetString("title_assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breathing Exercises.
        /// </summary>
        internal static string title_breathing {
            get {
                return ResourceManager.GetString("title_breathing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Evaluation of Fluency.
        /// </summary>
        internal static string title_evaluation {
            get {
                return ResourceManager.GetString("title_evaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexible rate of speech.
        /// </summary>
        internal static string title_flexible {
            get {
                return ResourceManager.GetString("title_flexible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیلف مینجمنٹ.
        /// </summary>
        internal static string title_management {
            get {
                return ResourceManager.GetString("title_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy Onset.
        /// </summary>
        internal static string title_onset {
            get {
                return ResourceManager.GetString("title_onset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stutter Rater.
        /// </summary>
        internal static string title_rater {
            get {
                return ResourceManager.GetString("title_rater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Rating of Stuttering.
        /// </summary>
        internal static string title_rating {
            get {
                return ResourceManager.GetString("title_rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string title_settings {
            get {
                return ResourceManager.GetString("title_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggers of Stuttering.
        /// </summary>
        internal static string triggers_heading {
            get {
                return ResourceManager.GetString("triggers_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stuttering may be worse when the person is excited, tired or under stress, or when feeling self-conscious, hurried or pressured. Certain situations such as speaking in front of a group or talking on the phone can be particularly difficult for people who stutter..
        /// </summary>
        internal static string triggers_para {
            get {
                return ResourceManager.GetString("triggers_para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urdu.
        /// </summary>
        internal static string urdu {
            get {
                return ResourceManager.GetString("urdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stuttering Varies.
        /// </summary>
        internal static string varies_heading {
            get {
                return ResourceManager.GetString("varies_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People do not stutter the same way or the same amount in all situations. Variability can also confuse parents, teachers, and peers, for they may wonder why a person is fluent in one situation but struggles in another. It is not because the speaker is not trying hard enough; it is just because stuttering varies..
        /// </summary>
        internal static string varies_para {
            get {
                return ResourceManager.GetString("varies_para", resourceCulture);
            }
        }
    }
}
